format_examples = {
    "Box 1": [
        "sales within uae",
        "vat on local sales",
        "domestic sales with vat",
        "customer name",
        "customer trn",
        "customer tax registration number",
        "clear description of the supply",
        "supply description",
        "supply",
        "customer"
    ],
    "Box 4": [
        "exports to other gcc countries",
        "sales to vat-registered buyers outside uae",
        "clear description of the supply",
        "supply description",
        "supply",
        "customer name",
        "customer trn",
        "customer tax registration number",
        "location of the customer",
        "location",
        "customer location",
        "customer"
    ],
    "OOS": [
        "out-of-scope transactions",
        "sales from designated free zones",
        "goods sold without vat due to location",
        "customer name",
        "customer trn",
        "clear description of the supply",
        "supply description",
        "supply",
        "reason of out-of-scope sales treatment",
        "reason for out of scope",
        "out of scope"
    ],
    "Box 3": [
        "goods imported without customs",
        "non-declared imports",
        "supplier name",
        "supplier",
        "location of the supplier",
        "supplier location",    
        "clear description of the transaction",
        "transaction description",
        "transaction"
    ],
    "Box 6/7": [
        "imported goods cleared with customs declaration",
        "customs-cleared imports",
        "supplier name",
        "location of the supplier",
        "supplier location",
        "name of the customs authority",
        "customs declaration number",
        "clear description of the transaction",
        "transaction description",
        "transaction"
    ],
    "Box 9": [
        "reverse charge vat on services",
        "services from overseas suppliers",
        "supplier name",
        "supplier trn",
        "supplier tax registration number",
        "tax invoice",
        "tax credit note received date",
        "date received",
        "clear description of the supply",
        "supply description",
        "supply",
        "vat amount recovered",
        "vat adjustments"

    ],
    "SAR": [
        "pending supplier payments",
        "overdue invoices for vendors",
        "supplier balance report",
        "s.no",
        "serial number",
        "supplier name",
        "voucher no",
        "voucher number",
        "invoice no",
        "invoice number",
        "invoice date",
        "due date",
        "total invoice amount",
        "vat amount",
        "amount paid",
        "pending amount",
        "upto 30 days due",
        "upto thirty days due",
        "30-60 days due",
        "thirty to sixty days due",
        "61-90 days due",
        "sixty one to ninety days due",
        "more than 90 days due",
        "more than ninety days due",
        "pending >180 days",
        "more than one hundred eighty days due",
        "pending for more than one hundred and eighty days",
        "total days due from due date as on 16 may 2025"
    ],
    "vat": [
        "vat amount",
        "vat",
        "value added tax"
        ]
}

common = {"Common":[
        "transaction type",
        "taxpayer trn",
        "company name",
        "member company name",
        "tax invoice",
        "tax credit note no",
        "tax credit note number"
        "tax invoice",
        "tax credit note date",
        "tax invoice",
        "tax credit note amount",
        "before vat",
        "reporting period from",
        "reporting period to",
    ],
}